### PR TITLE
Posts appear with newest posts first

### PR DESCRIPTION
**Pull request by aballal**

### CODE REVIEW

**Review by i-hardy — APPROVED** [review]
:shipit:

**Review by dbugsy — CHANGES_REQUESTED** [review]
Please add tests

**Review by meta-morpho-sys — APPROVED** [review]
:shipit:

**Comment by aballal** [comment]
Added feature test for displaying posts in reverse order. Please review pull request.

**Review by dbugsy — APPROVED** [review]
:shipit: :shipit:

**Comment by dbugsy** [comment]
@aballal @meta-morpho-sys please pull the travis.yml across and then amend the commit - then feel free to merge once the build is passing :)

**Comment by ghost** [comment]
All changes in this pull request are already in the following pull: 
"Posts show the date they were posted #6"

**Pull request closed without merging**
